ProjetoCOTI_C#/SGH/SGH.Web/Controllers/MedicacaoController.cs
using SGH.Application.Contracts;
using SGH.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SGH.Web.Controllers
{
    [Authorize] //somente usuários autenticados
    public class MedicacaoController : Controller
    {
        private IAppServiceMedicacao appMedicacao;

        public MedicacaoController(IAppServiceMedicacao appMedicacao)
        {
            this.appMedicacao = appMedicacao;
        }
        // GET: Medicacao
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Create()
        {
            return View();
        }

        public JsonResult Salvar(string nomeMedicacao, string descricaoMedicacao)
        {
            try
            {
                Medicacao m = new Medicacao()
                {
                    Nome = nomeMedicacao,
                    Descricao = descricaoMedicacao
                };

                appMedicacao.Create(m);
                                   
                return Json(m);
               
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }

        }

        public JsonResult Alterar(int idMedicacao, string nomeMedicacao, string descricaoMedicacao)
        {
            try
            {
                Medicacao m = appMedicacao.FindById(idMedicacao);

                m.Nome = nomeMedicacao;
                m.Descricao = descricaoMedicacao;

                appMedicacao.Update(m);
                return Json(m);

            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }

        }
        public JsonResult CarregarMedicamentos()
        {
            try
            {
                StringBuilder dados = new StringBuilder();

                foreach (Medicacao m in appMedicacao.FindAll())
                {
                    dados.Append("<tr>");
                    dados.AppendFormat("<td> {0} </td>", m.IdMedicacao);
                    dados.AppendFormat("<td> {0} </td>", m.Nome);
                    dados.AppendFormat("<td> {0} </td>", m.Descricao);                   
                    dados.AppendFormat("<td> <a href='Update?id={0}' class='btn btn-warning btn-sm'> Alterar </a>  ", m.IdMedicacao);
                    dados.AppendFormat("<a href='Delete?id={0}' class='btn btn-danger btn-sm'> Excluir </a></td>", m.IdMedicacao);
                    dados.Append("</tr>");
                }

                return Json(dados.ToString());
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        public JsonResult ConsultarMedicamentos(string nome)
        {
            try
            {
                StringBuilder dados = new StringBuilder();

                foreach (Medicacao m in appMedicacao.FindAllByName(nome))
                {
                    dados.Append("<tr>");
                    dados.AppendFormat("<td> {0} </td>", m.IdMedicacao);
                    dados.AppendFormat("<td> {0} </td>", m.Nome);
                    dados.AppendFormat("<td> {0} </td>", m.Descricao);
                    dados.AppendFormat("<td> <a href='Update?id={0}' class='btn btn-warning btn-sm'> Alterar </a>  ", m.IdMedicacao);
                    dados.AppendFormat("<a href='Delete?id={0}' class='btn btn-danger btn-sm'> Excluir </a></td>", m.IdMedicacao);
                    dados.Append("</tr>");
                }

                return Json(dados.ToString());
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        public ActionResult Update(int id)
        {
            Medicacao m = appMedicacao.FindById(id);
            return View(m);
        }
        public ActionResult Delete(int id)
        {
            try
            {
                Medicacao m = appMedicacao.FindById(id);
                if (m != null)
                {
                    appMedicacao.Delete(m);
                    return RedirectToAction("Index", "Funcionario");
                }

                return RedirectToAction("Index", "Paciente");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Index", "Paciente");
                // return Json(ex.Message);
            }
        }

        public ActionResult ListarMedicamentos()
        {
            List<Medicacao> m = appMedicacao.FindAll();
            return Json(m, JsonRequestBehavior.AllowGet);
        }
    }
}

ProjetoCOTI_C#/SGH/SGH.Web/Controllers/TratamentoHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGH.Web.Controllers
{
    [Authorize] //somente usuários autenticados
    public class TratamentoHomeController : Controller
    {
        // GET: Tratamento
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProjetoCOTI_C#/SGH/SGH.Web/Views/TratamentoHome/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<style>
    /*Author: Kosmom.ru*/ .loading, .loading > td, .loading > th, .nav li.loading.active > a, .pagination li.loading, .pagination > li.active.loading > a, .pager > li.loading > a {
        background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, rgba(0, 0, 0, 0) 25%, rgba(0, 0, 0, 0) 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, rgba(0, 0, 0, 0) 75%, rgba(0, 0, 0, 0));
        background-size: 150px 150px;
        animation: 2s linear 0s normal none infinite progress-bar-stripes;
        -webkit-animation: progress-bar-stripes 2s linear infinite;
    }

    .btn.btn-default.loading, input[type="text"].loading, select.loading, textarea.loading, .well.loading, .list-group-item.loading, .pagination > li.active.loading > a, .pager > li.loading > a {
        background-image: linear-gradient(45deg, rgba(235, 235, 235, 0.15) 25%, rgba(0, 0, 0, 0) 25%, rgba(0, 0, 0, 0) 50%, rgba(235, 235, 235, 0.15) 50%, rgba(235, 235, 235, 0.15) 75%, rgba(0, 0, 0, 0) 75%, rgba(0, 0, 0, 0));
    }

    .loading {
        width: 150px;
        height: 150px;
        font-size: 20px;
    }

    p {
        margin-top: 50px;
    }

    .containers {
        background-color: red;
    }

    a {
        padding: 100px;
    }

    .espaco {
        width: 150px;
        height: 150px;
    }

    .magin {
        margin-left: 50px;
    }
</style>

<div class="container">
    <div class="row">
        <div class="espaco"></div>
        @*<div class="espaco"></div>*@
        <div class="col-md-12 magin">
            <div class="col-md-3">

            </div>
            <div class="col-md-3">
                <a href="@(Url.Action("Index", "Tratamento"))" class="btn btn-primary loading"><p>Tratamento</p></a>
            </div>
            <div class="col-md-3">
                <a href="@(Url.Action("Index", "Medicacao"))" class="btn btn-success loading"><p>Medicação</p></a>
            </div>
            <div class="col-md-3">

            </div>
        </div>
    </div>
</div>