ProjetoCOTI_C#/SGH/SGH.Web/Controllers/AdministradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGH.Web.Controllers
{
    [Authorize] //somente usuários autenticados
    public class AdministradorController : Controller
    {
        [HttpGet, OutputCache(NoStore = true, Duration = 1)]
        // GET: Administrador
        public ActionResult Index()
        {
            return View();
        }     
    }
}

ProjetoCOTI_C#/SGH/SGH.Web/Controllers/HomeController.cs
using SGH.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGH.Web.Controllers
{
    [Authorize] //somente usuários autenticados
    public class HomeController : Controller
    {
        // GET: Home
        [HttpGet, OutputCache(NoStore = true, Duration = 1)]
        public ActionResult Index()
        {
            Funcionario f = Session["usuario_autenticado"] as Funcionario;

            return View(f);
        }
    }
}

ProjetoCOTI_C#/SGH/SGH.Web/Controllers/TratamentoHomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGH.Web.Controllers
{
    [Authorize] //somente usuários autenticados
    public class TratamentoHomeController : Controller
    {
        // GET: Tratamento
        public ActionResult Index()
        {
            return View();
        }
    }
}

ProjetoCOTI_C#/SGH/SGH.Web/Views/Home/IAdministrador.cshtml
<div class="col-md-3">
    <a class="btn btn-primary loading" href='@(Url.Action("Index", "Paciente"))'><p>Paciente</p></a>
</div>
<div class="col-md-3">
    <a class="btn btn-danger loading" href='@(Url.Action("Index", "Consulta"))'><p>Consulta</p></a>
</div>
<div class="col-md-3">
    <a class="btn btn-success loading" href='@(Url.Action("Index", "TratamentoHome"))'><p>Tratamento</p></a>
</div>
<div class="col-md-3">
    <a class="btn btn-info loading" href='@(Url.Action("Index", "Administrador"))'><p>Administrador</p></a>
</div>        

ProjetoCOTI_C#/SGH/SGH.Web/Views/Home/IFuncionario.cshtml
<div class="col-md-3">
   
</div>
<div class="col-md-3">
    <a class="btn btn-primary loading" href='@(Url.Action("Index", "Paciente"))'><p>Paciente</p></a>
</div>
<div class="col-md-3">
    <a class="btn btn-danger loading" href='@(Url.Action("Index", "Consulta"))'><p>Consulta</p></a>
</div>
<div class="col-md-3">
    
</div>  

ProjetoCOTI_C#/SGH/SGH.Web/Views/Home/IMedico.cshtml
<div class="col-md-3">

</div>
<div class="col-md-3">
    <a class="btn btn-danger loading" href='@(Url.Action("Index", "Consulta"))'><p>Consulta</p></a>
</div>
<div class="col-md-3">
    <a class="btn btn-success loading" href='@(Url.Action("Index", "Tratamento"))'><p>Tratamento</p></a>
</div>
<div class="col-md-3">

</div> 

ProjetoCOTI_C#/SGH/SGH.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using SGH.Entities;
@model Funcionario
<style>
    /*Author: Kosmom.ru*/.loading,.loading>td,.loading>th,.nav li.loading.active>a,.pagination li.loading,.pagination>li.active.loading>a,.pager>li.loading>a{
    background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, rgba(0, 0, 0, 0) 25%, rgba(0, 0, 0, 0) 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, rgba(0, 0, 0, 0) 75%, rgba(0, 0, 0, 0));
    background-size: 150px 150px;
    animation: 2s linear 0s normal none infinite progress-bar-stripes;
    -webkit-animation: progress-bar-stripes 2s linear infinite;
}
.btn.btn-default.loading,input[type="text"].loading,select.loading,textarea.loading,.well.loading,.list-group-item.loading,.pagination>li.active.loading>a,.pager>li.loading>a{
background-image: linear-gradient(45deg, rgba(235, 235, 235, 0.15) 25%, rgba(0, 0, 0, 0) 25%, rgba(0, 0, 0, 0) 50%, rgba(235, 235, 235, 0.15) 50%, rgba(235, 235, 235, 0.15) 75%, rgba(0, 0, 0, 0) 75%, rgba(0, 0, 0, 0));
}

.loading{
    width:150px;
    height: 150px;
    font-size: 20px;
}

p{
    margin-top: 50px;
}

.containers{
    background-color:red;
}

a{
    padding:100px;
}
.espaco{
    width:150px;
    height: 150px;
}
.magin
{
    margin-left: 50px;
}
</style>
<div class="container">
    <div class="row">
        <div class="espaco"></div>
        @*<div class="espaco"></div>*@
        <div class="col-md-12 magin">
            @if (Model.perfil.Equals("a"))
            {
                @Html.Partial("IAdministrador")
            }
            else if (Model.perfil.Equals("m"))
            {
                @Html.Partial("IMedico")
            }
            else if (Model.perfil.Equals("f"))
            {
                @Html.Partial("IFuncionario")
            }
            else
            {
                <p>Perfil não encontrado!</p>
            }
        </div>
        

    </div>
</div>

        <!-- INICIO MODAL AICIONAR -->
<div class="modal fade" id="modalTipoContratacao">
    <div class="modal-dialog">
        <div class="modal-content borda-redonda" style="overflow:auto">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title"><i class="glyphicon glyphicon-list-alt"></i>&nbsp;Perfil do Usuário</h4>
            </div>
            <div class="modal-body">
                <table id="tabela" class="table table-striped table-hover">
                    <thead>
                        <tr>
                            <th>Nome</th>
                            <th>Email</th>
                            <th>Data de Cadastro</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>
                                <input type="text" class="form-control" id="cmdNomeUsuario" value="@Model.Nome" disabled/>
                            </td>
                            <td>
                                <input type="text" class="form-control" id="cmdLoginUsuario" value="@Model.Login" disabled/>
                            </td>
                            <td>
                                <input type="text" class="form-control" id="cmdDataCadastro" value="@Model.DataCadastroFormatada" disabled />
                            </td>
                        </tr>
                    </tbody>
                </table>              
            </div>

            <div class="modal-footer">
                <button class="btn btn-small" data-dismiss="modal" id="btnCancelarTipoContratacao">
                    Cancelar
                </button>               
            </div>
        </div>
    </div>
</div>