ProjetoCOTI_C#/SGH/SGH.Web/Controllers/PacienteController.cs
using SGH.Application.Contracts;
using SGH.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SGH.Web.Controllers
{
    [Authorize] //somente usuários autenticados
    public class PacienteController : Controller
    {
        private IAppServicePaciente appPaciente;
        private IAppServiceEndereco appEndereco;
        private IAppServiceTelefone appTelefone;

        public PacienteController(IAppServicePaciente appPaciente, IAppServiceEndereco appEndereco, IAppServiceTelefone appTelefone)
        {
            this.appPaciente = appPaciente;
            this.appEndereco = appEndereco;
            this.appTelefone = appTelefone;
        }

        [HttpGet, OutputCache(NoStore = true, Duration = 1)]
        // GET: Paciente
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Salvar(string nomePaciente, string emailPaciente, string sexoPaciente, string dataNascimento, 
                                    string logradouro, string bairro, string cidade, string estado, string cep)
        {
            try
            {
                Funcionario f = Session["usuario_autenticado"] as Funcionario;
                Paciente p = new Paciente()
                {
                    Nome = nomePaciente,
                    Email = emailPaciente,
                    Sexo = sexoPaciente,
                    DataNascimento = DateTime.Parse(dataNascimento),
                    IdFuncionario = f.IdFuncionario
                };
                
                Endereco e = new Endereco()
                {
                    Logradouro = logradouro,
                    Bairro = bairro,
                    Cidade = cidade,
                    Estado = estado,
                    Cep = Int32.Parse(cep)                   
                };
                
                p.Endereco = new List<Endereco>();
                p.Endereco.Add(e);
                p.Telefone = Session["telefoneSession"] as List<Telefone>;             
                appPaciente.Create(p);
                Session.Remove("telefoneSession");

                return RedirectToAction("Index", "Paciente");
            }
            catch (Exception ex)
            {
                return RedirectToAction("Erro", "Paciente");
            }
            
        }

        public JsonResult Alterar(string idPaciente, string idEndereco, string nomePaciente, string emailPaciente, string sexoPaciente, string dataNascimento,
                                    string logradouro, string bairro, string cidade, string estado, string cep)
        {
            try
            {
                Funcionario f = Session["usuario_autenticado"] as Funcionario;
                Paciente p = appPaciente.FindById(Int32.Parse(idPaciente));

                p.Nome = nomePaciente;
                p.Email = emailPaciente;
                p.Sexo = sexoPaciente;
                p.DataNascimento = DateTime.Parse(dataNascimento);

                Endereco e = appEndereco.FindById(Int32.Parse(idEndereco));

                e.Logradouro = logradouro;
                e.Bairro = bairro;
                e.Cidade = cidade;
                e.Estado = estado;
                e.Cep = Int32.Parse(cep);
                

                p.Endereco = new List<Endereco>();
                p.Endereco.Add(e);

                List<Telefone> telExclusao = Session["telefoneSessionExclusao"] as List<Telefone>;
                if (telExclusao != null)
                {
                    foreach (Telefone t in telExclusao)
                    {                      
                        appTelefone.Delete(t);
                    }
                }

                List<Telefone> tel = Session["telefoneSession"] as List<Telefone>;
               
                if (tel != null)
                {
                    foreach (Telefone t in tel.Where(t => t.IdPaciente == 0))
                    {
                        t.IdPaciente = Int32.Parse(idPaciente);
                        appTelefone.Create(t);
                    }
                }

                appPaciente.Update(p);

                Session.Remove("telefoneSession");
                Session.Remove("telefoneSessionExclusao");
                return Json("");
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }

        }
        //[HttpGet]
        public JsonResult CarregarPacientes()
        {
            try
            {
                StringBuilder dados = new StringBuilder();

                foreach (Paciente p in appPaciente.FindAll())
                {
                    string telefone = "";
                    dados.Append("<tr>");
                    dados.AppendFormat("<td> {0} </td>", p.IdPaciente);
                    dados.AppendFormat("<td> {0} </td>", p.Nome);
                    dados.AppendFormat("<td> {0} </td>", p.Email);
                    dados.AppendFormat("<td> {0} </td>", p.Sexo);
                    dados.AppendFormat("<td> {0:dd/MM/yyyy} </td>", p.DataNascimento);
                    foreach (Telefone t in appTelefone.FindByIdPaciente(p.IdPaciente))
                    {
                        telefone = telefone + t.NumeroTel.ToString();
                    }
                    dados.AppendFormat("<td> {0} </td>", telefone);
                    foreach (Endereco e in appEndereco.FindByIdPaciente(p.IdPaciente))
                    {
                        dados.AppendFormat("<td> {0} </td>", e.Estado);
                        dados.AppendFormat("<td> {0} </td>", e.Cidade);
                        dados.AppendFormat("<td> {0} </td>", e.Bairro);
                        dados.AppendFormat("<td> {0} </td>", e.Cep);
                    }
                    dados.AppendFormat("<td> <a href='Update?id={0}' class='btn btn-warning btn-sm'> Alterar </a>  ", p.IdPaciente);
                    dados.AppendFormat("<a href='Delete?id={0}' class='btn btn-danger btn-sm'> Excluir </a></td>", p.IdPaciente);                  
                    dados.Append("</tr>");
                }

                return Json(dados.ToString());
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        public JsonResult ConsultarPacientes(string nome)
        {
            try
            {
                StringBuilder dados = new StringBuilder();
                string telefone = "";
                foreach (Paciente p in appPaciente.FindAllByName(nome))
                {
                    //p.Endereco = new List<Endereco>();
                    //p.Endereco = appEndereco.FindByIdPaciente(p.IdPaciente);
                    //p.Telefone = new List<Telefone>();
                    //p.Telefone = appTelefone.FindByIdPaciente(p.IdPaciente);
                                                                                                                                                
                    dados.Append("<tr>");
                    dados.AppendFormat("<td> {0} </td>", p.IdPaciente);
                    dados.AppendFormat("<td> {0} </td>", p.Nome);
                    dados.AppendFormat("<td> {0} </td>", p.Email);
                    dados.AppendFormat("<td> {0} </td>", p.Sexo);
                    dados.AppendFormat("<td> {0:dd/MM/yyyy} </td>", p.DataNascimento);
                    foreach (Telefone t in appTelefone.FindByIdPaciente(p.IdPaciente))
                    {
                        telefone = telefone + t.NumeroTel.ToString();
                    }
                    dados.AppendFormat("<td> {0} </td>", telefone);
                    foreach (Endereco e in appEndereco.FindByIdPaciente(p.IdPaciente))
                    {
                        dados.AppendFormat("<td> {0} </td>", e.Estado);
                        dados.AppendFormat("<td> {0} </td>", e.Cidade);
                        dados.AppendFormat("<td> {0} </td>", e.Bairro);
                        dados.AppendFormat("<td> {0} </td>", e.Cep);
                    }
                    dados.AppendFormat("<td> <a href='Update?id={0}' class='btn btn-warning btn-sm'> Alterar </a>  ", p.IdPaciente);
                    dados.AppendFormat("<a href='Delete?id={0}' class='btn btn-danger btn-sm'> Excluir </a></td>", p.IdPaciente);
                    dados.Append("</tr>");
                }

                return Json(dados.ToString());
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        public ActionResult Update(int id)
        {
            Paciente p = appPaciente.FindById(id);
            Session["telefoneSession"] = p.Telefone;
            return View(p);
        }

        public ActionResult Delete(int id)
        {
            Paciente p = appPaciente.FindById(id);
            
            if (p != null)
            {
                //foreach (Telefone t in p.Telefone)
                //{
                //    appTelefone.Delete(t);
                //}
                //foreach (Endereco e in p.Endereco)
                //{
                //    appEndereco.Delete(e);
                //}
                appPaciente.Delete(p);
            }
            return RedirectToAction("Index", "Paciente");
            //return View("Index");
        }

        public ActionResult ListarPacientes()
        {
            List<Paciente> p = appPaciente.FindAll();
            return Json(p, JsonRequestBehavior.AllowGet);
        }
    }
}

ProjetoCOTI_C#/SGH/SGH.Web/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SGH.Web.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        // GET: Report
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Paciente()
        {
            return View();
        }

        public ActionResult Consulta()
        {
            return View();
        }

        public ActionResult Tratamento()
        {
            return View();
        }
    }
}

ProjetoCOTI_C#/SGH/SGH.Web/Controllers/TratamentoController.cs
using SGH.Application.Contracts;
using SGH.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace SGH.Web.Controllers
{
    public class TratamentoController : Controller
    {
        private IAppServiceTratamento appTratamento;
        private IAppServiceConsulta appConsulta;
        private IAppServiceMedicacao appMedicacao;

        public TratamentoController(IAppServiceTratamento appTratamento, IAppServiceConsulta appConsulta, IAppServiceMedicacao appMedicacao)
        {
            this.appTratamento = appTratamento;
            this.appConsulta = appConsulta;
            this.appMedicacao = appMedicacao;
        }
        // GET: Tratamento
        [Authorize]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        public ActionResult Update(int id)
        {
            Tratamento t = appTratamento.FindById(id);
            t.Consulta = appConsulta.FindById(t.IdConsulta);
            t.Medicacao = appMedicacao.FindById(t.IdMedicacao);

            return View(t);
        }
        public JsonResult Salvar(string descricaoTratamento, string idConsulta, string idMedicacao)
        {
            try
            {
                Tratamento t = new Tratamento()
                {
                    Descricao = descricaoTratamento,
                    IdConsulta = Int32.Parse(idConsulta),
                    IdMedicacao = Int32.Parse(idMedicacao)
                };

                appTratamento.Create(t);
                return Json(t);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        public JsonResult Alterar(string idTratamento, string descricaoTratamento, string idConsulta, string idMedicacao)
        {
            try
            {
                Tratamento t = appTratamento.FindById(Int32.Parse(idTratamento));

                t.Descricao = descricaoTratamento;
                t.IdConsulta = Int32.Parse(idConsulta);
                t.IdMedicacao = Int32.Parse(idMedicacao);

                appTratamento.Update(t);
                return Json(t);
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        public ActionResult Delete(int id)
        {
            Tratamento t = appTratamento.FindById(id);
            if (t != null)
            {
                appTratamento.Delete(t);
            }
            return RedirectToAction("Index", "Tratamento");
        }

        public JsonResult CarregarTratamentos()
        {
            try
            {
                StringBuilder dados = new StringBuilder();

                foreach (Tratamento t in appTratamento.FindAll())
                {
                    t.Consulta = appConsulta.FindById(t.IdConsulta);
                    t.Medicacao = appMedicacao.FindById(t.IdMedicacao);

                    dados.Append("<tr style='text - align:center'>");
                    dados.AppendFormat("<td> {0} </td>", t.IdTratamento);
                    dados.AppendFormat("<td> {0} </td>", t.Descricao);
                    dados.AppendFormat("<td> {0} - {1} </td>", t.Consulta.IdConsulta, t.Consulta.Hora);
                    dados.AppendFormat("<td> {0} - {1} </td>", t.Medicacao.IdMedicacao, t.Medicacao.Nome);
                    if (t.Consulta.Data >= DateTime.Today)
                    {
                        dados.AppendFormat("<td> <a href='Update?id={0}' class='btn btn-warning btn-sm'> Alterar </a>  ", t.IdTratamento);
                        dados.AppendFormat("<a href='Delete?id={0}' class='btn btn-danger btn-sm'> Excluir </a></td>", t.IdTratamento);
                    }
                    else
                    {
                        dados.Append("<td></td>");
                    }
                    dados.Append("</tr>");
                }

                return Json(dados.ToString());
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }

        public JsonResult ConsultarTratamentos(string dataConsulta)
        {
            try
            {
                StringBuilder dados = new StringBuilder();

                foreach (Consulta c in appConsulta.FindAllByData(DateTime.Parse(dataConsulta)))
                {
                    if (c != null)
                    {
                        Tratamento t = appTratamento.FindByIdConsulta(c.IdConsulta);

                        if (t != null)
                        {
                            t.Consulta = appConsulta.FindById(t.IdConsulta);
                            t.Medicacao = appMedicacao.FindById(t.IdMedicacao);

                            dados.Append("<tr style='text - align:center'>");
                            dados.AppendFormat("<td> {0} </td>", t.IdTratamento);
                            dados.AppendFormat("<td> {0} </td>", t.Descricao);
                            dados.AppendFormat("<td> {0} - {1} </td>", t.Consulta.IdConsulta, t.Consulta.Hora);
                            dados.AppendFormat("<td> {0} - {1} </td>", t.Medicacao.IdMedicacao, t.Medicacao.Nome);
                            if (t.Consulta.Data >= DateTime.Today)
                            {
                                dados.AppendFormat("<td> <a href='Update?id={0}' class='btn btn-warning btn-sm'> Alterar </a>  ", t.IdTratamento);
                                dados.AppendFormat("<a href='Delete?id={0}' class='btn btn-danger btn-sm'> Excluir </a></td>", t.IdTratamento);
                            }
                            else
                            {
                                dados.Append("<td></td>");
                            }
                            dados.Append("</tr>");
                        }
                        
                    }
                    
                }

                return Json(dados.ToString());
            }
            catch (Exception ex)
            {
                return Json(ex.Message);
            }
        }
    }
}

ProjetoCOTI_C#/SGH/SGH.Web/Views/Report/Consulta.cshtml
@{
    ViewBag.Title = "Consulta";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <h2>Relatório de Consultas</h2>
    <hr />
</div>

<iframe id="iFrameReportViewer" src="~/Reports/ReportConsulta.aspx" style="width: 99%; height: 3500px" scrolling="no" frameborder="0"></iframe>

ProjetoCOTI_C#/SGH/SGH.Web/Views/Report/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@*@section javascript{
<script>
    $(function () {
       // Report();

    });

    function Report() {
        url = "~/Reports/ReportConsulta.aspx";
        
        var myFrame = document.getElementById("iFrameReportViewer");
        if (myFrame !== null) {
            if (myFrame.src) {
                myFrame.src = url;
            }
            else if (myFrame.contentWindow !== null && myFrame.contentWindow.location !== null) {
                myFrame.contentWindow.location = url;
            }
            else {
                myFrame.setAttribute('src', url);
            }
        }
        return false;
    }

</script>
}*@
<style>
    /*Author: Kosmom.ru*/ .loading, .loading > td, .loading > th, .nav li.loading.active > a, .pagination li.loading, .pagination > li.active.loading > a, .pager > li.loading > a {
        background-image: linear-gradient(45deg, rgba(255, 255, 255, 0.15) 25%, rgba(0, 0, 0, 0) 25%, rgba(0, 0, 0, 0) 50%, rgba(255, 255, 255, 0.15) 50%, rgba(255, 255, 255, 0.15) 75%, rgba(0, 0, 0, 0) 75%, rgba(0, 0, 0, 0));
        background-size: 150px 150px;
        animation: 2s linear 0s normal none infinite progress-bar-stripes;
        -webkit-animation: progress-bar-stripes 2s linear infinite;
    }

    .btn.btn-default.loading, input[type="text"].loading, select.loading, textarea.loading, .well.loading, .list-group-item.loading, .pagination > li.active.loading > a, .pager > li.loading > a {
        background-image: linear-gradient(45deg, rgba(235, 235, 235, 0.15) 25%, rgba(0, 0, 0, 0) 25%, rgba(0, 0, 0, 0) 50%, rgba(235, 235, 235, 0.15) 50%, rgba(235, 235, 235, 0.15) 75%, rgba(0, 0, 0, 0) 75%, rgba(0, 0, 0, 0));
    }

    .loading {
        width: 150px;
        height: 150px;
        font-size: 20px;
    }

    p {
        margin-top: 50px;
    }

    .containers {
        background-color: red;
    }

    a {
        padding: 100px;
    }

    .espaco {
        width: 150px;
        height: 150px;
    }

    .magin {
        margin-left: 50px;
    }
</style>

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <h2>Relatórios</h2>
    <hr />
</div>

<div class="container">
    <div class="col-md-2">
        
    </div>
    <div class="col-md-3">
        <a class="btn btn-primary loading" href='@(Url.Action("Paciente", "Report"))'><p>Pacientes</p></a>
    </div>
    <div class="col-md-3">
        <a class="btn btn-danger loading" href='@(Url.Action("Consulta", "Report"))'><p>Consultas</p></a>
    </div>
    <div class="col-md-3">
        <a class="btn btn-success loading" href='@(Url.Action("Tratamento", "Report"))'><p>Tratamentos</p></a>
    </div>
</div>
  

@*<iframe  id="iFrameReportViewer" src="~/Reports/ReportConsulta.aspx" style="width: 99%; height: 3500px" scrolling="no" frameborder="0"></iframe>*@
      
@*<a href="~/Reports/ReportConsulta.aspx">~/Reports/ReportConsulta.aspx</a>*@

ProjetoCOTI_C#/SGH/SGH.Web/Views/Report/Paciente.cshtml
@{
    ViewBag.Title = "Paciente";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <h2>Relatório de Pacientes</h2>
    <hr />
</div>

<iframe  id="iFrameReportViewer" src="~/Reports/ReportPaciente.aspx" style="width: 99%; height: 3500px" scrolling="no" frameborder="0"></iframe>

ProjetoCOTI_C#/SGH/SGH.Web/Views/Report/Tratamento.cshtml
@{
    ViewBag.Title = "Tratamento";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <h2>Relatório de Tratamentos</h2>
    <hr />
</div>

<iframe id="iFrameReportViewer" src="~/Reports/ReportTratamento.aspx" style="width: 99%; height: 3500px" scrolling="no" frameborder="0"></iframe>